services:
  mnestix-browser:
    container_name: mnestix-browser
    image: !reset null
    build:
      target: dev
    environment:
      THEME_PRIMARY_COLOR: '#005962'
      THEME_SECONDARY_COLOR: '#147f8a'
      THEME_LOGO_URL: ''
    volumes:
      - ./src:/app/src
      - ./public:/app/public
#      - ./data/logo.svg:/app/public/logo

  mongodb:
    ports:
      - '27017:27017'

  aas-environment:
    ports:
      - '8081:8081'
        
  aas-discovery:
    ports:
      - '8082:8081'
