services:
  mnestix-browser:
    image: mnestix/mnestix-browser:latest
    container_name: mnestix-browser
    build:
      context: ../.
      dockerfile: Dockerfile
      target: dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ../src:/app/src
      - ../public:/app/public
    #     - ./data/logo.svg:/app/public/logo
    environment:
      REGISTRY_API_URL: 'http://localhost:8083'
      DISCOVERY_API_URL: 'http://localhost:5064/discovery'
      AAS_REPO_API_URL: 'http://localhost:5064/repo'
      MNESTIX_BACKEND_API_URL: 'http://localhost:5064'
      AD_CLIENT_ID: ${AD_CLIENT_ID}
      AD_TENANT_ID: ${AD_TENANT_ID}
      APPLICATION_ID_URI: 'api://mnestix-test-web-api/'
      AAS_LIST_FEATURE_FLAG: "true"
      COMPARISON_FEATURE_FLAG: "true"
      AUTHENTICATION_FEATURE_FLAG: "true"
      LOCK_TIMESERIES_PERIOD_FEATURE_FLAG: "true"
      THEME_PRIMARY_COLOR: '#005962'
      THEME_SECONDARY_COLOR: '#147f8a'
      THEME_LOGO_URL: ''
      KEYCLOAK_ENABLED: "false"
      KEYCLOAK_CLIENT_ID: "mnestix-browser-client-demo"
      KEYCLOAK_CLIENT_SECRET: "<client_secret>"
      KEYCLOAK_ISSUER: "http://localhost:9096/realms/BaSyx"
      KEYCLOAK_REFRESH_TOKEN_URL: "http://localhost:9096/realms/BaSyx/protocol/openid-connect/token"
      KEYCLOAK_END_SESSION_URL: "http://localhost:9096/realms/BaSyx/protocol/openid-connect/logout"
      KEYCLOAK_LOGOUT_REDIRECT: "http://localhost:300"
      NEXTAUTH_URL: "http://localhost:3000"