services:
  mnestix-browser:
    container_name: mnestix-browser
    image: !reset null
    build:
      target: dev
    volumes:
      - ../src:/app/src
      - ../public:/app/public
#      - ./data/logo.svg:/app/public/logo

  mongodb:
    ports:
      - '27017:27017'

  aas:
    ports:
      - '8081:8081'
