services:
  mnestix-browser:
    image: mnestix/mnestix-browser:latest # Using the pipeline image
    container_name: mnestix-browser
    build:
      context: ../.
      dockerfile: Dockerfile
      target: dev
    restart: always
    ports:
      - '3000:3000'
    volumes:
      - ../src:/app/src
      - ../public:/app/public
#     - ./data/logo.svg:/app/public/logo
    environment:
      REGISTRY_API_URL: 'http://localhost:8083'
      DISCOVERY_API_URL: 'http://localhost:5064/discovery'
      AAS_REPO_API_URL: 'http://localhost:5064/repo'
      MNESTIX_BACKEND_API_URL: 'http://localhost:5064'
      AD_CLIENT_ID: ${AD_CLIENT_ID}
      AD_TENANT_ID: ${AD_TENANT_ID}
      APPLICATION_ID_URI: 'api://mnestix-test-web-api/'
      AAS_LIST_FEATURE_FLAG: true
      COMPARISON_FEATURE_FLAG: true
      AUTHENTICATION_FEATURE_FLAG: true
      LOCK_TIMESERIES_PERIOD_FEATURE_FLAG: true
      THEME_PRIMARY_COLOR: '#0d4453'
      THEME_SECONDARY_COLOR: '#147f8a'
#      THEME_LOGO_MIME_TYPE: 'image/svg+xml'
      THEME_LOGO_URL: https://xitaso.com/wp-content/uploads/XITASO-Logo-quer.svg
